repositoryUrl: https://github.com/dynamsoft-docs/code-parser-docs-server/blob/main
repository: dynamsoft-docs/code-parser-docs-server
docFullPath: https://www.dynamsoft.com/code-parser/docs-archive/server
firstLevelUrl: /code-parser/docs-archive/server/
docHomePage: /code-parser/docs-archive/core/introduction/

dcp_cpp: /code-parser/docs-archive/server/programming/cplusplus/
dcp_cpp_api: /code-parser/docs-archive/server/programming/cplusplus/api-reference/
dcp_cpp_release_notes: /code-parser/docs-archive/server/programming/cplusplus/release-notes/

dcp_dotnet: /code-parser/docs-archive/server/programming/dotnet/
dcp_dotnet_api: /code-parser/docs-archive/server/programming/dotnet/api-reference/
dcp_dotnet_release_notes: /code-parser/docs-archive/server/programming/dotnet/release-notes/

assets: /code-parser/docs-archive/server/assets/
edit_icon: /code-parser/docs-archive/server/assets/img-icon/edit-icon.png
smile_icon: /code-parser/docs-archive/server/assets/img-icon/icon-smile.png
sad_icon: /code-parser/docs-archive/server/assets/img-icon/icon-sad.png

dcp_release_notes: /code-parser/docs-archive/core/release-notes/
dcp_code_types: /code-parser/docs-archive/core/code-types/
dcp_parameters: /code-parser/docs-archive/core/parameters/

dcv_enumerations: /capture-vision/docs-archive/core/enums/
dcv_parameters: /capture-vision/docs-archive/core/parameters/
dcv_cpp_api: /capture-vision/docs-archive/server/programming/cplusplus/api-reference/
dcv_dotnet_api: /capture-vision/docs-archive/server/programming/dotnet/api-reference/

useVersionTree: true

baseurl: "/code-parser/docs-archive/server"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

edition: desktop

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "programming/cplusplus" 
    values: 
      docRootName: "Code Parser C++ Edition" 
      docHomePage: "/code-parser/docs-archive/server/programming/cplusplus/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root

