repositoryUrl: https://github.com/dynamsoft-docs/code-parser-docs-server/blob/main
repository: dynamsoft-docs/code-parser-docs-server
docFullPath: https://www.dynamsoft.com/code-parser/docs/server
firstLevelUrl: /code-parser/docs/server/
docHomePage: /code-parser/docs/core/introduction/
needSearchIndex: true
searchNeedFilter: true

dcp_cpp: /code-parser/docs/server/programming/cplusplus/
dcp_cpp_api: /code-parser/docs/server/programming/cplusplus/api-reference/
dcp_cpp_release_notes: /code-parser/docs/server/programming/cplusplus/release-notes/

dcp_dotnet: /code-parser/docs/server/programming/dotnet/
dcp_dotnet_api: /code-parser/docs/server/programming/dotnet/api-reference/
dcp_dotnet_release_notes: /code-parser/docs/server/programming/dotnet/release-notes/

dcp_python: /code-parser/docs/server/programming/python/
dcp_python_api: /code-parser/docs/server/programming/python/api-reference/
dcp_python_release_notes: /code-parser/docs/server/programming/python/release-notes/

assets: /code-parser/docs/server/assets/
edit_icon: /code-parser/docs/server/assets/img-icon/edit-icon.png
smile_icon: /code-parser/docs/server/assets/img-icon/icon-smile.png
sad_icon: /code-parser/docs/server/assets/img-icon/icon-sad.png

dcp_release_notes: /code-parser/docs/core/release-notes/
dcp_code_types: /code-parser/docs/core/code-types/
dcp_parameters: /code-parser/docs/core/parameters/

dcvb_enumerations: /capture-vision/docs/core/enums/
dcvb_parameters: /capture-vision/docs/core/parameters/
dcvb_cpp_api: /capture-vision/docs/server/programming/cplusplus/api-reference/
dcvb_dotnet_api: /capture-vision/docs/server/programming/dotnet/api-reference/
dcvb_python_api: /capture-vision/docs/server/programming/python/api-reference/

useVersionTree: false
isDCV: true

baseurl: "/code-parser/docs/server"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

edition: desktop

defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "programming/cplusplus" 
    values: 
      docRootName: "Code Parser C++ Edition" 
      docHomePage: "/code-parser/docs/server/programming/cplusplus/"
  - scope: 
      path: "programming/dotnet" 
    values: 
      docRootName: "Code Parser .NET Edition" 
      docHomePage: "/code-parser/docs/server/programming/dotnet/"
  - scope: 
      path: "programming/python" 
    values: 
      docRootName: "Code Parser Python Edition" 
      docHomePage: "/code-parser/docs/server/programming/python/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root

