useGroupedVersion: true

version_info_list_desktop:
  - value: latest version
  - value: 2.x
    child:
      - 2.2.10_cplusplus
      - 2.2.0_cplusplus
      - 2.0.20_cplusplus
      - 2.0.10_cplusplus
      - 2.0.0_cplusplus
